'use client';

import { MovieCard } from '@/components/movie-card';
import type { Movie } from '@/lib/types';

const categories = [
  {
    title: 'Trending',
    movies: [
      { title: 'Fighter', year: 2024, description: 'Top IAF aviators assemble for a perilous mission.', imdbRating: 7.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/fighter/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6amIq_mP4xM' },
      { title: 'Animal', year: 2023, description: 'A son\'s tumultuous relationship with his father spirals into a bloody gang war.', imdbRating: 6.8, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/animal/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Dydmpfo68DA' },
      { title: 'Jawan', year: 2023, description: 'A man is driven by a personal vendetta to rectify the wrongs in society.', imdbRating: 7.8, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/jawan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=COv52Qyctws' },
      { title: 'Pathaan', year: 2023, description: 'An Indian agent races against a doomsday clock to stop a ruthless mercenary with a bitter past.', imdbRating: 6.8, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/pathaan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=vqu4z34wENw' },
      { title: 'Rocky Aur Rani Kii Prem Kahaani', year: 2023, description: 'A flamboyant Punjabi and a witty Bengali fall in love despite their differences.', imdbRating: 6.9, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/rockyrani/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6pyi3nN0R3k' },
      { title: 'Laapataa Ladies', year: 2024, description: 'Two young brides get swapped on a train. A search for them begins.', imdbRating: 8.5, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/laapataa/200/300', trailerUrl: 'https://www.youtube.com/watch?v=gaZ1z_m4x6k' },
      { title: 'Shaitaan', year: 2024, description: 'A family\'s idyllic getaway turns into a nightmare when a mysterious stranger enters their home.', imdbRating: 7.0, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/shaitaan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=pmyD0G5A3I4' },
      { title: 'Article 370', year: 2024, description: 'A young intelligence officer is recruited for a top-secret mission to crack down on terrorism and the conflict economy.', imdbRating: 8.2, platform: 'JioCinema', imageUrl: 'https://picsum.photos/seed/article370/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6e94pYwS2A8' },
      { title: 'Crew', year: 2024, description: 'Three hard-working women have their lives thrown into turmoil when they get involved in a smuggling ring.', imdbRating: 6.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/crew/200/300', trailerUrl: 'https://www.youtube.com/watch?v=D-a2_wA5_a0' },
      { title: 'Srikanth', year: 2024, description: 'The inspiring true story of a visually impaired entrepreneur who built a multi-crore company.', imdbRating: 8.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/srikanth/200/300', trailerUrl: 'https://www.youtube.com/watch?v=33f1c_sMh_s' },
      { title: 'Maidaan', year: 2024, description: 'The story of Syed Abdul Rahim, the architect of the golden era of Indian football.', imdbRating: 8.0, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/maidaan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=n_4k1uH6p_w' },
      { title: 'Chandu Champion', year: 2024, description: 'The real-life story of Murlikant Petkar, India\'s first Paralympic gold medalist.', imdbRating: 8.1, platform: 'In Theaters', imageUrl: 'https://picsum.photos/seed/chandu/200/300', trailerUrl: 'https://www.youtube.com/watch?v=aD4Q1f3v_s0' },
      { title: 'Stree 2', year: 2024, description: 'The follow-up to the hit horror-comedy, bringing back the mystery of the female ghost.', imdbRating: 7.5, platform: 'Upcoming', imageUrl: 'https://picsum.photos/seed/stree2/200/300', trailerUrl: 'https://www.youtube.com/watch?v=vDD4kL2dY6M' },
      { title: 'Bhool Bhulaiyaa 3', year: 2024, description: 'The third installment in the popular horror-comedy franchise.', imdbRating: 7.0, platform: 'Upcoming', imageUrl: 'https://picsum.photos/seed/bhool3/200/300', trailerUrl: 'https://www.youtube.com/watch?v=cIruG9b82v4' },
      { title: 'Singham Again', year: 2024, description: 'The next chapter in the cop universe, featuring the iconic Inspector Bajirao Singham.', imdbRating: 7.2, platform: 'Upcoming', imageUrl: 'https://picsum.photos/seed/singham3/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Azb2pZXJV-8' },
      { title: 'Munjya', year: 2024, description: 'A young man\'s visit to his native village unveils a family secret and a vengeful spirit.', imdbRating: 7.5, platform: 'In Theaters', imageUrl: 'https://picsum.photos/seed/munjya/200/300', trailerUrl: 'https://www.youtube.com/watch?v=f2a5Y4sJ8gE' },
      { title: 'Kalki 2898 AD', year: 2024, description: 'A modern-day avatar of Vishnu, arrives on Earth to protect the world from evil forces.', imdbRating: 8.5, platform: 'Upcoming', imageUrl: 'https://picsum.photos/seed/kalki/200/300', trailerUrl: 'https://www.youtube.com/watch?v=kQDd1Ahgp2M' },
      { title: 'Bad Newz', year: 2024, description: 'A comedy of errors ensues when two couples find themselves in a hilarious IVF mix-up.', imdbRating: 6.8, platform: 'Upcoming', imageUrl: 'https://picsum.photos/seed/badnewz/200/300', trailerUrl: 'https://www.youtube.com/watch?v=rWbV93sD4W0' },
      { title: 'Ishq Vishk Rebound', year: 2024, description: 'A reboot of the classic romantic comedy, exploring modern-day relationships.', imdbRating: 6.5, platform: 'In Theaters', imageUrl: 'https://picsum.photos/seed/ishqvishk/200/300', trailerUrl: 'https://www.youtube.com/watch?v=2Tj2Wsa41aA' },
      { title: 'Emergency', year: 2024, description: 'A political drama based on the life of former Prime Minister Indira Gandhi and the Indian Emergency.', imdbRating: 8.0, platform: 'Upcoming', imageUrl: 'https://picsum.photos/seed/emergency/200/300', trailerUrl: 'https://www.youtube.com/watch?v=3zD9i_b2-yY' },
    ],
  },
  {
    title: 'Bollywood Blockbusters',
    movies: [
      { title: '3 Idiots', year: 2009, description: 'Two friends searching for their long lost companion recall their college days and the memories of their friend who inspired them to think differently.', imdbRating: 8.4, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/3idiots/200/300', trailerUrl: 'https://www.youtube.com/watch?v=K0e-w_y-v-A' },
      { title: 'Dangal', year: 2016, description: 'Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games.', imdbRating: 8.4, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/dangal/200/300', trailerUrl: 'https://www.youtube.com/watch?v=x_7YlGv9u1g' },
      { title: 'Lagaan', year: 2001, description: 'The people of a small village in Victorian India stake their future on a game of cricket against their ruthless British rulers.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/lagaan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=oSgH6b2t3o8' },
      { title: 'Sholay', year: 1975, description: 'After his family is murdered by a notorious and ruthless bandit, a former police officer enlists the services of two outlaws to capture him.', imdbRating: 8.2, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/sholay/200/300', trailerUrl: 'https://www.youtube.com/watch?v=hB5z3c_A_pA' },
      { title: 'Dilwale Dulhania Le Jayenge', year: 1995, description: 'When Raj and Simran first met on an inter-rail holiday in Europe, it wasn\'t exactly Love at first sight but when Simran is taken to India for an arranged marriage, things change.', imdbRating: 8.1, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/ddlj/200/300', trailerUrl: 'https://www.youtube.com/watch?v=c25GKl5VNeY' },
      { title: 'Baahubali: The Beginning', year: 2015, description: 'In the kingdom of Mahishmati, a young man raised in a remote village discovers his royal heritage.', imdbRating: 8.0, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/baahubali/200/300', trailerUrl: 'https://www.youtube.com/watch?v=sOEg_z4W1B4' },
      { title: 'Bajrangi Bhaijaan', year: 2015, description: 'An Indian man with a magnanimous heart takes a young mute Pakistani girl back to her homeland to reunite her with her family.', imdbRating: 8.1, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/bajrangi/200/300', trailerUrl: 'https://www.youtube.com/watch?v=4VG_g_m_4aA' },
      { title: 'PK', year: 2014, description: 'An alien on Earth loses the remote to his spaceship. His innocent questions and childlike curiosity force people to re-examine their beliefs.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/pk/200/300', trailerUrl: 'https://www.youtube.com/watch?v=SOXWc32k42o' },
      { title: 'Gadar: Ek Prem Katha', year: 2001, description: 'A Sikh truck driver falls in love with a Muslim girl during the 1947 partition of India.', imdbRating: 7.3, platform: 'Zee5', imageUrl: 'https://picsum.photos/seed/gadar/200/300', trailerUrl: 'https://www.youtube.com/watch?v=63w_J8v4a0s' },
      { title: 'K.G.F: Chapter 2', year: 2022, description: 'The blood-soaked land of Kolar Gold Fields has a new overlord now. Rocky, whose name strikes fear in the heart of his foes.', imdbRating: 8.3, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/kgf2/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Qah9sSIXJqk' },
      { title: 'Kabhi Khushi Kabhie Gham...', year: 2001, description: 'A family drama about a wealthy family torn apart by a marriage against the patriarch\'s wishes.', imdbRating: 7.4, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/k3g/200/300', trailerUrl: 'https://www.youtube.com/watch?v=2wn32fS_w-w' },
      { title: 'Kal Ho Naa Ho', year: 2003, description: 'A terminally ill man tries to set up his best friend with the woman he loves.', imdbRating: 7.9, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/khnh/200/300', trailerUrl: 'https://www.youtube.com/watch?v=g0eO74g_s_o' },
      { title: 'Zindagi Na Milegi Dobara', year: 2011, description: 'Three friends on a bachelor trip in Spain learn some lessons about life and themselves.', imdbRating: 8.2, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/znmd/200/300', trailerUrl: 'https://www.youtube.com/watch?v=BQRi4z1i7g0' },
      { title: 'Yeh Jawaani Hai Deewani', year: 2013, description: 'A coming-of-age story about two people who meet during a trekking trip and fall in love.', imdbRating: 7.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/yjhd/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Rbp2XUSez_I' },
      { title: 'Chennai Express', year: 2013, description: 'A man\'s journey from Mumbai to Rameshwaram becomes an unexpected adventure.', imdbRating: 6.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/chennai/200/300', trailerUrl: 'https://www.youtube.com/watch?v=hK3g1nF_p8c' },
      { title: 'Swades', year: 2004, description: 'A successful Indian scientist returns to an Indian village to take his nanny to America with him and in the process rediscovers his roots.', imdbRating: 8.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/swades/200/300', trailerUrl: 'https://www.youtube.com/watch?v=f2igB6s9s28' },
      { title: 'Rang De Basanti', year: 2006, description: 'The story of six young Indians who assist an English woman to film a documentary on the freedom fighters from their past.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/rangde/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6lE5s14T15g' },
      { title: 'Mughal-E-Azam', year: 1960, description: 'A 16th century prince falls in love with a court dancer and battles with his emperor father.', imdbRating: 8.1, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/mughaleazam/200/300', trailerUrl: 'https://www.youtube.com/watch?v=r_b3fV1a44M' },
      { title: 'Mother India', year: 1957, description: 'In the absence of her husband, a poverty-stricken woman raises her sons through many trials and tribulations.', imdbRating: 8.0, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/motherindia/200/300', trailerUrl: 'https://www.youtube.com/watch?v=4T1bH2y6x2Y' },
      { title: 'Anand', year: 1971, description: 'The story of a terminally ill man who wishes to live his life to the fullest before he passes away.', imdbRating: 8.2, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/anand/200/300', trailerUrl: 'https://www.youtube.com/watch?v=e_p3wL8JG0k' },
    ],
  },
  {
    title: 'Sports',
    movies: [
      { title: '83', year: 2021, description: 'The story of India\'s incredible cricket World Cup victory in 1983.', imdbRating: 7.4, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/83/200/300', trailerUrl: 'https://www.youtube.com/watch?v=C6M5x22Z648' },
      { title: 'Bhaag Milkha Bhaag', year: 2013, description: 'The true story of the "Flying Sikh" - world champion runner and Olympian Milkha Singh.', imdbRating: 8.2, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/milkha/200/300', trailerUrl: 'https://www.youtube.com/watch?v=y3g0c0sA1fE' },
      { title: 'Chak De! India', year: 2007, description: 'A disgraced hockey player coaches the Indian women\'s national hockey team to victory.', imdbRating: 8.2, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/chakde/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6a0-dSMw5vA' },
      { title: 'Mary Kom', year: 2014, description: 'A chronicle of the life of Indian boxer Mary Kom, who went through several hardships before audaciously accomplishing her ultimate dream.', imdbRating: 6.8, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/marykom/200/300', trailerUrl: 'https://www.youtube.com/watch?v=O3_s23i4t5o' },
      { title: 'M.S. Dhoni: The Untold Story', year: 2016, description: 'The untold story of Mahendra Singh Dhoni\'s journey from ticket collector to trophy collector - the world-cup-winning captain of the Indian Cricket Team.', imdbRating: 7.9, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/dhoni/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6L6XqWoS8tw' },
      { title: 'Paan Singh Tomar', year: 2012, description: 'The story of a soldier and athlete who becomes a dacoit.', imdbRating: 8.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/paansingh/200/300', trailerUrl: 'https://www.youtube.com/watch?v=h10g7a_v9vA' },
      { title: 'Sultan', year: 2016, description: 'A middle-aged wrestling champion tries to make a comeback to represent India at the Olympics.', imdbRating: 7.0, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/sultan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=wPxqcq6Byq0' },
      { title: 'Iqbal', year: 2005, description: 'A deaf-and-mute boy from a remote Indian village dreams of playing cricket for India.', imdbRating: 8.1, platform: 'Zee5', imageUrl: 'https://picsum.photos/seed/iqbal/200/300', trailerUrl: 'https://www.youtube.com/watch?v=yY19i3pL1XQ' },
      { title: 'Soorma', year: 2018, description: 'The inspiring true story of the comeback of hockey player Sandeep Singh.', imdbRating: 7.4, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/soorma/200/300', trailerUrl: 'https://www.youtube.com/watch?v=c7M_d9s4_f4' },
      { title: 'Gold', year: 2018, description: 'The journey of a man who was instrumental in India\'s first Olympic gold medal as a free nation.', imdbRating: 7.3, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/gold/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Pcv0b4k3p5E' },
      { title: 'Saala Khadoos', year: 2016, description: 'A former boxer quits boxing but coaches a fisherwoman to fulfill his dream.', imdbRating: 7.6, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/saala/200/300', trailerUrl: 'https://www.youtube.com/watch?v=132uT67M-cE' },
      { title: 'Jersey', year: 2022, description: 'A talented but failed cricketer decides to return to cricket in his late thirties.', imdbRating: 7.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/jersey/200/300', trailerUrl: 'https://www.youtube.com/watch?v=y31hJ5S3nF0' },
      { title: 'Toofaan', year: 2021, description: 'An orphan from Dongri grows up to be a local goon but his life changes when he meets Ananya.', imdbRating: 6.9, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/toofaan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=25pE4E3v1f8' },
      { title: 'Rashmi Rocket', year: 2021, description: 'A small-town girl who overcomes all societal barriers to become a national-level athlete.', imdbRating: 7.1, platform: 'Zee5', imageUrl: 'https://picsum.photos/seed/rashmi/200/300', trailerUrl: 'https://www.youtube.com/watch?v=b_hE6C9a_9Y' },
      { title: 'Shabaash Mithu', year: 2022, description: 'The life of Mithali Raj, the captain of the Indian women\'s cricket team.', imdbRating: 5.7, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/mithu/200/300', trailerUrl: 'https://www.youtube.com/watch?v=P2L39S1P_pA' },
      { title: 'Jhund', year: 2022, description: 'Based on the life of Vijay Barse, a retired sports teacher who founded an NGO called Slum Soccer.', imdbRating: 7.4, platform: 'Zee5', imageUrl: 'https://picsum.photos/seed/jhund/200/300', trailerUrl: 'https://www.youtube.com/watch?v=L_1i3f4vKkQ' },
      { title: 'Budhia Singh: Born to Run', year: 2016, description: 'The story of the world\'s youngest marathon runner, Budhia Singh.', imdbRating: 7.4, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/budhia/200/300', trailerUrl: 'https://www.youtube.com/watch?v=iE3w3v31iG4' },
      { title: 'Ghoomer', year: 2023, description: 'The story of a paraplegic sportswoman, who is a cricket prodigy.', imdbRating: 7.7, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/ghoomer/200/300', trailerUrl: 'https://www.youtube.com/watch?v=1YxS_e-gS4w' },
      { title: 'Dangal Girls', year: 2017, description: 'A documentary on the Phogat sisters, their training and their journey to the Commonwealth Games.', imdbRating: 7.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/dangalgirls/200/300', trailerUrl: 'https://www.youtube.com/watch?v=FolAqgVoN_8' },
      { title: 'Sachin: A Billion Dreams', year: 2017, description: 'A documentary on the life of Indian cricket icon Sachin Tendulkar.', imdbRating: 8.6, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/sachin/200/300', trailerUrl: 'https://www.youtube.com/watch?v=pP3B_g9Uu9A' },
    ],
  },
  {
    title: 'Drama',
    movies: [
      { title: 'Gangs of Wasseypur', year: 2012, description: 'A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, and a bloody blending of revenge, politics and power.', imdbRating: 8.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/wasseypur/200/300', trailerUrl: 'https://www.youtube.com/watch?v=j-Ak2rf_6_g' },
      { title: 'Queen', year: 2013, description: 'A Delhi girl from a traditional family sets out on a solo honeymoon after her marriage gets canceled.', imdbRating: 8.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/queen/200/300', trailerUrl: 'https://www.youtube.com/watch?v=KGC6vl3lzf0' },
      { title: 'Barfi!', year: 2012, description: 'Three young people learn that love can neither be defined nor contained by society\'s definition of normal and abnormal.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/barfi/200/300', trailerUrl: 'https://www.youtube.com/watch?v=61hA_m23P6E' },
      { title: 'My Name Is Khan', year: 2010, description: 'An Indian Muslim man with Asperger\'s syndrome takes a challenge to speak to the President of the United States, and embarks on a cross-country journey.', imdbRating: 8.0, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/mynameiskhan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Jz_xW3F1PXI' },
      { title: 'Taare Zameen Par', year: 2007, description: 'An eight-year-old boy is thought to be a lazy trouble-maker, until the new art teacher has the patience and compassion to discover the real problem behind his struggles in school.', imdbRating: 8.4, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/taare/200/300', trailerUrl: 'https://www.youtube.com/watch?v=tn_2Ie_g4kU' },
      { title: 'Andhadhun', year: 2018, description: 'A series of mysterious events change the life of a blind pianist, who must report a crime that he should technically not know about.', imdbRating: 8.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/andhadhun/200/300', trailerUrl: 'https://www.youtube.com/watch?v=2iVYI99VGaw' },
      { title: 'Pink', year: 2016, description: 'When three young women are implicated in a crime, a retired lawyer steps forward to help them clear their names.', imdbRating: 8.1, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/pink/200/300', trailerUrl: 'https://www.youtube.com/watch?v=WHg3s2R1b-g' },
      { title: 'Haider', year: 2014, description: 'A young man returns to Kashmir after his father\'s disappearance to confront his uncle - the man who has a relationship with his mother.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/haider/200/300', trailerUrl: 'https://www.youtube.com/watch?v=93x_n_hD0cQ' },
      { title: 'A Wednesday', year: 2008, description: 'A retiring police commissioner recounts the most memorable case of his career wherein he was informed about a bomb scare in Mumbai.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/wednesday/200/300', trailerUrl: 'https://www.youtube.com/watch?v=f3yS1d34i20' },
      { title: 'Drishyam', year: 2015, description: 'Desperate measures are taken by a man who tries to save his family from the dark side of the law, after they commit an unexpected crime.', imdbRating: 8.2, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/drishyam/200/300', trailerUrl: 'https://www.youtube.com/watch?v=AuuX2j14NBg' },
      { title: 'Udta Punjab', year: 2016, description: 'A story that revolves around drug abuse in the affluent north Indian State of Punjab.', imdbRating: 7.8, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/udta/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Xy11-2nG3uM' },
      { title: 'Talvar', year: 2015, description: 'An experienced investigator confronts several conflicting theories about the perpetrators of a violent double homicide.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/talvar/200/300', trailerUrl: 'https://www.youtube.com/watch?v=aQ2sI-3hG6s' },
      { title: 'Neerja', year: 2016, description: 'The story of the courageous Neerja Bhanot, who sacrificed her life while protecting the lives of 359 passengers on a hijacked plane.', imdbRating: 7.6, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/neerja/200/300', trailerUrl: 'https://www.youtube.com/watch?v=7779eG_K34w' },
      { title: 'Kapoor & Sons', year: 2016, description: 'A dysfunctional family comes together for a reunion, and old tensions and secrets bubble to the surface.', imdbRating: 7.7, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/kapoor/200/300', trailerUrl: 'https://www.youtube.com/watch?v=s7b21_q2w2g' },
      { title: 'Padmaavat', year: 2018, description: 'Set in medieval Rajasthan, Queen Padmavati is married to a noble king and they live in a prosperous fortress with their subjects until an ambitious Sultan hears of Padmavati\'s beauty.', imdbRating: 7.0, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/padmaavat/200/300', trailerUrl: 'https://www.youtube.com/watch?v=X_5_BLt76c0' },
      { title: 'Udaan', year: 2010, description: 'Expelled from his school, a 16-year-old boy returns home to his abusive and oppressive father.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/udaan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=bZ_g1gY9yYk' },
      { title: 'Black', year: 2005, description: 'The cathartic story of a young woman who can\'t see, hear, or speak, and the teacher who brings a ray of light into her dark world.', imdbRating: 8.2, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/black/200/300', trailerUrl: 'https://www.youtube.com/watch?v=H4hJ1gA8x0g' },
      { title: 'The Lunchbox', year: 2013, description: 'A mistaken delivery in Mumbai\'s famously efficient lunchbox delivery system connects a young housewife to an older man in the dusk of his life as they build a fantasy world together through notes in the lunchbox.', imdbRating: 7.8, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/lunchbox/200/300', trailerUrl: 'https://www.youtube.com/watch?v=sK2-t5d5i9M' },
      { title: 'Piku', year: 2015, description: 'A quirky comedy about the relationship between a daughter and her aging father, whose eccentricities drive everyone crazy.', imdbRating: 7.6, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/piku/200/300', trailerUrl: 'https://www.youtube.com/watch?v=z2Bp_g4b_c0' },
      { title: 'Masaan', year: 2015, description: 'Four lives intersect along the Ganges: a low caste boy hopelessly in love, a daughter ridden with guilt of a sexual encounter ending in a tragedy, a hapless father with fading morality, and a spirited child yearning for a family.', imdbRating: 8.1, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/masaan/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6aygG3fA5xI' },
    ],
  },
  {
    title: 'Web Series',
    movies: [
      { title: 'Mirzapur', year: 2018, description: 'A shocking incident at a wedding procession ignites a series of events entangling the lives of two families in the lawless city of Mirzapur.', imdbRating: 8.5, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/mirzapur/200/300', trailerUrl: 'https://www.youtube.com/watch?v=ZNeGF-t5MhE' },
      { title: 'Sacred Games', year: 2018, description: 'A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.', imdbRating: 8.6, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/sacredgames/200/300', trailerUrl: 'https://www.youtube.com/watch?v=w-xen3k_5L0' },
      { title: 'The Family Man', year: 2019, description: 'A working man from the National Investigation Agency tries to protect the nation from terrorism, but he also has to protect his family from the impact of his secretive, high-pressure job.', imdbRating: 8.7, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/familyman/200/300', trailerUrl: 'https://www.youtube.com/watch?v=XatRGut65VI' },
      { title: 'Panchayat', year: 2020, description: 'A comedy-drama, which captures the journey of an engineering graduate Abhishek, who for lack of a better job option joins as secretary of a Panchayat office in a remote village of Uttar Pradesh.', imdbRating: 8.9, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/panchayat/200/300', trailerUrl: 'https://www.youtube.com/watch?v=mojZJ79VRqg' },
      { title: 'Scam 1992: The Harshad Mehta Story', year: 2020, description: 'Set in 1980s and 90s Bombay, it follows the life of Harshad Mehta, a stockbroker who took the stock market to dizzying heights and his catastrophic downfall.', imdbRating: 9.3, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/scam1992/200/300', trailerUrl: 'https://www.youtube.com/watch?v=ISOkxS4iF2M' },
      { title: 'Asur: Welcome to Your Dark Side', year: 2020, description: 'A unique crime thriller that pits two opposing worlds against each other. The less explored, intricate world of forensic science and the deep mysticism of ancient Indian Mythology.', imdbRating: 8.5, platform: 'JioCinema', imageUrl: 'https://picsum.photos/seed/asur/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Lh9iS4M1x4Y' },
      { title: 'Special OPS', year: 2020, description: 'The story of a RAW agent who draws parallels between terrorist attacks and believes a single mastermind is behind them all.', imdbRating: 8.6, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/specialops/200/300', trailerUrl: 'https://www.youtube.com/watch?v=31vB9xT0M3o' },
      { title: 'Gullak', year: 2019, description: 'A collection of disarming and relatable tales of the Mishra family.', imdbRating: 9.1, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/gullak/200/300', trailerUrl: 'https://www.youtube.com/watch?v=4xV2mYw_hJk' },
      { title: 'Delhi Crime', year: 2019, description: 'Based on the 2012 Delhi gang rape case, this series follows the Delhi Police investigation into finding the men who perpetrated the crime.', imdbRating: 8.5, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/delhicrime/200/300', trailerUrl: 'https://www.youtube.com/watch?v=jNuK12f3p5g' },
      { title: 'Kota Factory', year: 2019, description: 'Set in Kota, a hub for many coaching centres, the show follows the life of a 16-year-old who is preparing for his entrance exams.', imdbRating: 9.0, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/kota/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6xK1f4x3C4I' },
      { title: 'Made in Heaven', year: 2019, description: 'It is the story of two wedding planners in Delhi, where tradition jostles with modern aspirations against the backdrop of big fat Indian weddings.', imdbRating: 8.3, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/madeinheaven/200/300', trailerUrl: 'https://www.youtube.com/watch?v=4M_c1aH80bA' },
      { title: 'Paatal Lok', year: 2020, description: 'A down and out cop lands the case of a lifetime when four suspects are nabbed in the assassination attempt of a prime time journalist.', imdbRating: 8.0, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/paatallok/200/300', trailerUrl: 'https://www.youtube.com/watch?v=c6t4w9I3M3g' },
      { title: 'Aarya', year: 2020, description: 'When her world suddenly turns upside down, will Aarya become the very thing she has always hated?', imdbRating: 7.8, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/aarya/200/300', trailerUrl: 'https://www.youtube.com/watch?v=t5QW1p7g3yQ' },
      { title: 'Rocket Boys', year: 2022, description: 'The story of two extraordinary men, Dr. Homi J. Bhabha and Dr. Vikram Sarabhai, who created history while building India\'s future.', imdbRating: 8.9, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/rocketboys/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Z5sK4bEaY-A' },
      { title: 'Jubilee', year: 2023, description: 'The story of the passion, dreams, ambition and love of a group of people in the world of Hindi cinema.', imdbRating: 8.3, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/jubilee/200/300', trailerUrl: 'https://www.youtube.com/watch?v=6J_2bYyS45A' },
      { title: 'Farzi', year: 2023, description: 'An artist who gets pulled into the murky high stakes of a con job and a fiery task force officer on the mission to rid the country of his menaces in a fast-paced, edgy one-of-a-kind thriller.', imdbRating: 8.4, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/farzi/200/300', trailerUrl: 'https://www.youtube.com/watch?v=p_0K1s_8m6M' },
      { title: 'Dahaad', year: 2023, description: 'A female inspector investigates a case of multiple women found dead in public bathrooms.', imdbRating: 7.6, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/dahaad/200/300', trailerUrl: 'https://www.youtube.com/watch?v=CqY2mT6vT3E' },
      { title: 'Aspirants', year: 2021, description: 'The story of the journey of three UPSC (public service competitive exams in India for recruitment to various civil services) aspirants and their friendship against all odds.', imdbRating: 9.2, platform: 'YouTube', imageUrl: 'https://picsum.photos/seed/aspirants/200/300', trailerUrl: 'https://www.youtube.com/watch?v=oT5gLg1b_4A' },
      { title: 'Breathe: Into the Shadows', year: 2020, description: 'A 6-year old girl is kidnapped by a mysterious masked man, who demands an unusual ransom. To save his daughter, Dr. Avinash Sabharwal must kill someone.', imdbRating: 7.7, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/breathe/200/300', trailerUrl: 'https://www.youtube.com/watch?v=i5zV9GqA3fE' },
      { title: 'Bandish Bandits', year: 2020, description: 'Radhe, a singing prodigy from a classical background, and Tamanna, a pop sensation, meet and fall in love.', imdbRating: 8.1, platform: 'Prime Video', imageUrl: 'https://picsum.photos/seed/bandish/200/300', trailerUrl: 'https://www.youtube.com/watch?v=uh-2zA2fT5M' },
    ],
  },
  {
    title: 'TV Shows',
    movies: [
      { title: 'Kaun Banega Crorepati', year: 2000, description: 'Indian version of the popular quiz show, "Who Wants to be a Millionaire?"', imdbRating: 7.2, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/kbc/200/300', trailerUrl: 'https://www.youtube.com/watch?v=z_S6R72pP2Y' },
      { title: 'Bigg Boss', year: 2006, description: 'Indian reality television game show based on the Dutch reality show Big Brother.', imdbRating: 5.1, platform: 'JioCinema', imageUrl: 'https://picsum.photos/seed/biggboss/200/300', trailerUrl: 'https://www.youtube.com/watch?v=n8qsV3uPjM8' },
      { title: 'The Kapil Sharma Show', year: 2016, description: 'A comedy and celebrity talk show hosted by Kapil Sharma.', imdbRating: 7.9, platform: 'Netflix', imageUrl: 'https://picsum.photos/seed/kapilsharma/200/300', trailerUrl: 'https://www.youtube.com/watch?v=j41T7gMAJ5I' },
      { title: 'Crime Patrol', year: 2003, description: 'A Hindi-language crime anthology series that presents dramatized versions of crime cases that occurred in India.', imdbRating: 7.7, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/crimepatrol/200/300', trailerUrl: 'https://www.youtube.com/watch?v=gUj51Wubd6k' },
      { title: 'CID', year: 1998, description: 'An Indian police procedural television series about the Criminal Investigation Department.', imdbRating: 8.1, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/cid/200/300', trailerUrl: 'https://www.youtube.com/watch?v=uyI-8g2L24E' },
      { title: 'Tarak Mehta Ka Ooltah Chashmah', year: 2008, description: 'The residents of a housing society help each other find solutions when they face common, real-life challenges.', imdbRating: 8.9, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/tmkoc/200/300', trailerUrl: 'https://www.youtube.com/watch?v=mD0D_y_A5yI' },
      { title: 'Shark Tank India', year: 2021, description: 'Aspiring entrepreneurs from India pitch their business models to a panel of investors and persuade them to invest money in their idea.', imdbRating: 8.8, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/sharktank/200/300', trailerUrl: 'https://www.youtube.com/watch?v=JbS311_JtWk' },
      { title: 'Anupamaa', year: 2020, description: 'A devoted housewife and mother excels in her family duties, but is often taken for granted.', imdbRating: 5.4, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/anupamaa/200/300', trailerUrl: 'https://www.youtube.com/watch?v=d_i8a5oWzro' },
      { title: 'Indian Idol', year: 2004, description: 'Indian version of the Pop Idol format that has aired on Sony Entertainment Television since 2004.', imdbRating: 5.6, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/indianidol/200/300', trailerUrl: 'https://www.youtube.com/watch?v=GdTfWqJ-h7c' },
      { title: 'Sarabhai vs Sarabhai', year: 2004, description: 'The shenanigans of a quintessential upper-class family in Mumbai.', imdbRating: 9.0, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/sarabhai/200/300', trailerUrl: 'https://www.youtube.com/watch?v=b74XGH1gJmU' },
      { title: 'Comedy Nights with Kapil', year: 2013, description: 'A comedy show with celebrity interviews and skits.', imdbRating: 7.4, platform: 'JioCinema', imageUrl: 'https://picsum.photos/seed/comedynights/200/300', trailerUrl: 'https://www.youtube.com/watch?v=3uU1S_z8sQk' },
      { title: 'Nach Baliye', year: 2005, description: 'A celebrity couple dance reality television show.', imdbRating: 6.5, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/nachbaliye/200/300', trailerUrl: 'https://www.youtube.com/watch?v=A8vHk9lT-C4' },
      { title: 'Jhalak Dikhhla Jaa', year: 2006, description: 'A celebrity dance competition based on the format of "Dancing with the Stars".', imdbRating: 6.3, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/jhalak/200/300', trailerUrl: 'https://www.youtube.com/watch?v=p-O08cEaY3A' },
      { title: 'MTV Roadies', year: 2003, description: 'A youth-based reality television show.', imdbRating: 6.7, platform: 'JioCinema', imageUrl: 'https://picsum.photos/seed/roadies/200/300', trailerUrl: 'https://www.youtube.com/watch?v=pSt5o3c2E0M' },
      { title: 'MasterChef India', year: 2010, description: 'A competitive cooking reality show based on the original British MasterChef.', imdbRating: 7.5, platform: 'SonyLIV', imageUrl: 'https://picsum.photos/seed/masterchef/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Sj5m1T9tWkY' },
      { title: 'Satyamev Jayate', year: 2012, description: 'A talk show that discusses and provides possible solutions to social issues in India.', imdbRating: 8.9, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/satyamev/200/300', trailerUrl: 'https://www.youtube.com/watch?v=4842t3a3dM0' },
      { title: 'Yeh Rishta Kya Kehlata Hai', year: 2009, description: 'A story of a young couple, Akshara and Naitik, who live in a Marwari joint family.', imdbRating: 5.2, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/yrkkh/200/300', trailerUrl: 'https://www.youtube.com/watch?v=Vl3sSsls-oE' },
      { title: 'Aap Ki Adalat', year: 1993, description: 'A popular Indian talk show where prominent personalities are cross-examined in a courtroom-like setting.', imdbRating: 8.0, platform: 'YouTube', imageUrl: 'https://picsum.photos/seed/adalat/200/300', trailerUrl: 'https://www.youtube.com/watch?v=FmZii0gEwSg' },
      { title: 'Sa Re Ga Ma Pa', year: 1995, description: 'One of the oldest running music reality shows in India.', imdbRating: 7.1, platform: 'Zee5', imageUrl: 'https://picsum.photos/seed/saregama/200/300', trailerUrl: 'https://www.youtube.com/watch?v=0kFm1gqERkI' },
      { title: 'Khichdi', year: 2002, description: 'A sitcom about a quirky Gujarati joint family living in an old mansion.', imdbRating: 8.7, platform: 'Disney+', imageUrl: 'https://picsum.photos/seed/khichdi/200/300', trailerUrl: 'https://www.youtube.com/watch?v=1t4iB43a8vE' },
    ],
  },
];

export default function HomePage() {
  return (
    <div className="container mx-auto py-10 px-4 sm:px-6 lg:px-8 space-y-12">
      {categories.map((category) => (
        <section key={category.title}>
          <h2 className="text-2xl font-bold font-headline mb-4 text-primary">{category.title}</h2>
          <div className="flex space-x-4 overflow-x-auto pb-4 -mx-4 px-4">
            {category.movies.map((movie: Movie) => (
              <div key={movie.title} className="w-48 flex-shrink-0">
                <MovieCard movie={movie} />
              </div>
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}
